# Trained with A5000 (24GB) x 5. It took about 8 days.
# The e_branchformer encoder_conf is based on:
# egs2/librispeech/asr1/conf/tuning/train_asr_e_branchformer.yaml

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

specaug: specaug
specaug_conf:
    apply_time_warp: false
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 1
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 1

encoder: e_branchformer
encoder_conf:
    output_size: 384
    attention_heads: 6
    attention_layer_type: selfattn
    pos_enc_layer_type: abs_pos
    rel_pos_type: latest
    attention_qk_norm: false    # qk norm
    use_flash_attn: true    # flash attn
    cgmlp_linear_units: 1536
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 6
    dropout_rate: 0.05
    positional_dropout_rate: 0.05
    attention_dropout_rate: 0.05
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 1536
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 6
    linear_units: 1536
    num_blocks: 6
    dropout_rate: 0.05
    positional_dropout_rate: 0.05
    self_attention_dropout_rate: 0.05
    src_attention_dropout_rate: 0.05
    self_attention_qk_norm: false   # qk norm
    src_attention_qk_norm: false    # qk norm
    self_attention_use_flash_attn: true
    src_attention_use_flash_attn: true

ctc_conf:
    ctc_type: stc
    stc_p0: 0.4
    stc_plast: 0.7
    stc_thalf: 15000

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# optim: adamw
# optim_conf:
#     lr: 1.0e-03
#     betas:
#     - 0.9
#     - 0.98
#     eps: 1.0e-06
#     weight_decay: 0.0
# scheduler: piecewiselinearwarmuplr
# scheduler_conf:
#     warmup_steps_list: [0, 7000, 20000]
#     warmup_lr_list: [0., 1.0e-04, 1.0e-03]

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 7000

use_amp: true
num_att_plot: 0
log_interval: 500
batch_type: numel
batch_bins: 100000000
accum_grad: 1
max_epoch: 70
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
num_workers: 8
unused_parameters: true
